# 2.4 Типы данных в Python Часть 1
## Специальные 
- отсутствие значения (`Null`: константа `None`)
- типовой объект (`Type`: результат `type()`)
- объект для создания срезов (`Ellipsis`: `...`)
- нереализованный в логических операциях объект(`NotImplemented`)
- ...

In [1]:
# примеры
None,type(1000),type(10e3),type(True),...,type(...)

(None, int, float, bool, Ellipsis, ellipsis)

In [2]:
import numpy as np
arr = np.arange(120).reshape(2,3,4,5)
print(arr.shape)
print(arr[0,:,:,0])
print(arr[0,...,0])

(2, 3, 4, 5)
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


In [3]:
numbers = ()
numbers = (1,)
numbers = (4, 5, 6, 99)

## Логические (`boolean`: `True`, `False`)
- константы

In [4]:
# логический объект
for el in [dir(True)[i:i+5] for i in range(0,75,5)]:
    print(el)

['__abs__', '__add__', '__and__', '__bool__', '__ceil__']
['__class__', '__delattr__', '__dir__', '__divmod__', '__doc__']
['__eq__', '__float__', '__floor__', '__floordiv__', '__format__']
['__ge__', '__getattribute__', '__getnewargs__', '__gt__', '__hash__']
['__index__', '__init__', '__init_subclass__', '__int__', '__invert__']
['__le__', '__lshift__', '__lt__', '__mod__', '__mul__']
['__ne__', '__neg__', '__new__', '__or__', '__pos__']
['__pow__', '__radd__', '__rand__', '__rdivmod__', '__reduce__']
['__reduce_ex__', '__repr__', '__rfloordiv__', '__rlshift__', '__rmod__']
['__rmul__', '__ror__', '__round__', '__rpow__', '__rrshift__']
['__rshift__', '__rsub__', '__rtruediv__', '__rxor__', '__setattr__']
['__sizeof__', '__str__', '__sub__', '__subclasshook__', '__truediv__']
['__trunc__', '__xor__', 'as_integer_ratio', 'bit_length', 'conjugate']
['denominator', 'from_bytes', 'imag', 'numerator', 'real']
['to_bytes']


In [5]:
True.as_integer_ratio(),True.__hash__(),False.__hash__()

((1, 1), 1, 0)

In [6]:
# сравнение
logic_exp1 = [3 > 2, 5 < 8,len('abc') == 1, 
              2 ** 3 >= 9, 11 <= 7, 7 != 12]
for le in logic_exp1: print(le, end=' ')

True True False False False True 

In [7]:
# логические выражения
logic_exp2 = [True and False, True or False, True or 0, 
              1 or False, True and 0, 1 and False,
              not False, not 1] 
for le in logic_exp2: print(le, end=" ")

False True True 1 0 False True False 

In [8]:
# побитовые выражения 
byte_exp1 = [True & False, True | False, 1 & 0, 0 | 1,
             1 | False, False | 1, 0 & True, True & 1, 
             ~ 0, ~ 1, ~ False, ~ True] 
for be in byte_exp1: print(be, end=' ')

False True 0 1 1 1 0 1 -1 -2 -1 -2 

In [9]:
# встроенная функция bool()
bool(None), not bool(None), not None, ~ bool(None)

(False, True, True, -1)

In [10]:
bool(0),bool(0j),bool(1),bool(-4.),bool(2j)

(False, False, True, True, True)

In [11]:
bool([1,2,3]),bool({1,2,3}),\
bool(list()),bool(tuple()),bool([]),bool({})

(True, True, False, False, False, False)

In [12]:
# логические законы и таблицы истинности
import numpy,sympy,itertools
sympy.init_printing(use_unicode=True)
from sympy.logic import simplify_logic,satisfiable
from sympy.logic import And,Or,Not,Xor,Implies,Equivalent
x1,x2,x3,x4,x5,x6,x7,x8,x9,x10=\
sympy.symbols('x1,x2,x3,x4,x5,x6,x7,x8,x9,x10')
eq1=Or(x1,Not(x2))&(x3|~x4)
eq2=Or(x3,Not(x4))&(x5|~x6)
eq3=Or(x5,Not(x6))&(x7|~x8)
eq4=Or(x7,Not(x8))&(x9|~x10)
eq=simplify_logic(And(eq1,eq2)&And(eq3,eq4))
s=list(satisfiable(eq,all_models=True))
eqsubs=eq.subs({x1:1,x2:1,x3:1,x4:1,x5:1,
                x6:1,x7:1,x8:1,x9:1,x10:1})
for el in [eq,eqsubs,s[0],eq.subs(s[1])]:
    print(el); print('\n')

(x1 | ~x2) & (x3 | ~x4) & (x5 | ~x6) & (x7 | ~x8) & (x9 | ~x10)


1


{x9: True, x3: True, x7: True, x1: True, x5: True, x6: False, x2: False, x8: False, x4: False, x10: False}


True




In [13]:
# sympy - как логические 
for (t1,t2) in [(False,False),(False,True),(True,False),(True,True)]:
    print((~x1 & ~x2).subs({x1:t1,x2:t2}),end=' ')
    print(And(Not(x1),Not(x2)).subs({x1:t1,x2:t2}))

True True
False False
False False
False False


## Строковые (`Text Sequence Type`: `str`)
- последовательный 
- неизменяемый

In [14]:
# отдельные символы, слова, фразы, предложения, тексты
# в системе Юникод
'hello', 'привет'

('hello', 'привет')

In [15]:
# строковый объект
for el in [dir('a')[i:i+5] for i in range(0,80,5)]:
    print(el)

['__add__', '__class__', '__contains__', '__delattr__', '__dir__']
['__doc__', '__eq__', '__format__', '__ge__', '__getattribute__']
['__getitem__', '__getnewargs__', '__gt__', '__hash__', '__init__']
['__init_subclass__', '__iter__', '__le__', '__len__', '__lt__']
['__mod__', '__mul__', '__ne__', '__new__', '__reduce__']
['__reduce_ex__', '__repr__', '__rmod__', '__rmul__', '__setattr__']
['__sizeof__', '__str__', '__subclasshook__', 'capitalize', 'casefold']
['center', 'count', 'encode', 'endswith', 'expandtabs']
['find', 'format', 'format_map', 'index', 'isalnum']
['isalpha', 'isascii', 'isdecimal', 'isdigit', 'isidentifier']
['islower', 'isnumeric', 'isprintable', 'isspace', 'istitle']
['isupper', 'join', 'ljust', 'lower', 'lstrip']
['maketrans', 'partition', 'replace', 'rfind', 'rindex']
['rjust', 'rpartition', 'rsplit', 'rstrip', 'split']
['splitlines', 'startswith', 'strip', 'swapcase', 'title']
['translate', 'upper', 'zfill']


In [16]:
# возвращает встроенная функция-конструктор str()
str(1),str((1,2,3,4,5,6,7)),str(list())

('1', '(1, 2, 3, 4, 5, 6, 7)', '[]')

In [17]:
# результат некоторых математических операций
bin(25),type(bin(25)),hex(25),type(hex(25))

('0b11001', str, '0x19', str)

In [18]:
# срезы строк
string = "абвгдеё"
# slice(сколько сначала), slice(старт,финиш-1,шаг)
string[slice(3)], string[slice(1,5,2)],\
string[:3], string[1:5:2]

('абв', 'бг', 'абв', 'бг')

In [19]:
# в обратном порядке, палиндром
string = "радар"
string[::-1], string == string[::-1]

('радар', True)

In [20]:
# соединение и повторение
2*'abc '+3*'def' 'ghi '

'abc abc defghi defghi defghi '

In [21]:
# совпадение и принадлежность
'a' == 'abc','a' != 'abc',\
'd' in 'abc','d' not in 'abc'

(False, True, False, True)

In [22]:
# с переменными, а не с литералами
a,abc = 'a','abc'
a is abc,a is not abc

(False, True)

In [23]:
# изменение объекта генератором
string = "123довод321"
gen = (x for x in string if not x.isdigit())
type(gen),''.join(gen)

(generator, 'довод')

In [24]:
# применение анонимной функции
string = "123ротор321"
''.join(filter(lambda x: not x.isdigit(), string))

'ротор'

In [25]:
# обработка с помощью регулярных выражений
import re
string = "123доход321"
pattern = r'[0-9]'
re.sub(pattern,'',string),re.sub(pattern,'@',string,3),\
re.split('2',string),re.split('2',string,1)

('доход', '@@@доход321', ['1', '3доход3', '1'], ['1', '3доход321'])

In [26]:
# проверка на наличие идентификаторов и ключевых слов
from keyword import iskeyword
'текст'.isidentifier(), iskeyword('текст'),\
'string'.isidentifier(), iskeyword('string'),\
'len'.isidentifier(), iskeyword('len'),\
'in'.isidentifier(), iskeyword('in')

(True, False, True, False, True, False, True, True)

In [27]:
# может быть идентификатором
len = len('123'); len

In [28]:
# переходит в другие типы
bool(''),bool('a'),bool('1'),int('1'),float('1.1')

(False, True, True, 1, 1.1)

In [29]:
# распадается на элементы-символы
list(string), tuple(string), set(string)

(['1', '2', '3', 'д', 'о', 'х', 'о', 'д', '3', '2', '1'],
 ('1', '2', '3', 'д', 'о', 'х', 'о', 'д', '3', '2', '1'),
 {'1', '2', '3', 'д', 'о', 'х'})

In [30]:
# огромное количество встроенных методов
trans1 = {65:122,97:90,122:66,90:98}
trans2 = {ord('A'):ord('z'),ord('a'):ord('Z'),
          ord('Z'):ord('b'),ord('z'):ord('B')}
st="AAAaaaZZZzzz"
st,st.translate(trans1),st.translate(trans2)

('AAAaaaZZZzzz', 'zzzZZZbbbBBB', 'zzzZZZbbbBBB')

In [31]:
# служебные символы можно игнорировать `\`
print('abc\tdef','abc\\tdef',sep='||')
print('abc" "def','abc\' \'def',sep='||')
# r-строки 
# исключающие последовательности не транслируются
print(r'abc\tdef',R'abc\' \'def',sep='||')

abc	def||abc\tdef
abc" "def||abc' 'def
abc\tdef||abc\' \'def


In [32]:
print("oct: \150\145\154\154\157, hex: \x68\x65\x6c\x6c\x6f")
print(r"oct: \147\145\154\154\157, hex: \x48\x65\x6c\x6c\x6f")
print('\u2192 \N{rightwards arrow}')
print(r'\u2192 \N{rightwards arrow}')
print("hello \bhello", R"hello \bhello")

oct: hello, hex: hello
oct: \147\145\154\154\157, hex: \x48\x65\x6c\x6c\x6f
→ →
\u2192 \N{rightwards arrow}
hello hello hello \bhello


In [33]:
# различные стили форматирования
print("int: %d, oct: %o, hex: %x"%(3*(65,)))

int: 65, oct: 101, hex: 41


In [34]:
# метод format()
'{:.2f}'.format(3.999)

'4.00'

In [35]:
# f-string
from datetime import datetime
now = datetime.now().strftime("%b/%d/%Y - %H:%M:%S")
f'{now = }'

"now = 'Dec/24/2022 - 14:56:57'"

## Числовые (`Numeric`: `int`, `float`, `complex`)
- целочисленные
- вещественные
- комплексные

!в различных системах счисления

In [36]:
# числовой объект
for n in [1, 1., 1+1j]:
    for el in [dir(n)[i:i+5] for i in range(0,75,5)]:
        print(el)
    print()

['__abs__', '__add__', '__and__', '__bool__', '__ceil__']
['__class__', '__delattr__', '__dir__', '__divmod__', '__doc__']
['__eq__', '__float__', '__floor__', '__floordiv__', '__format__']
['__ge__', '__getattribute__', '__getnewargs__', '__gt__', '__hash__']
['__index__', '__init__', '__init_subclass__', '__int__', '__invert__']
['__le__', '__lshift__', '__lt__', '__mod__', '__mul__']
['__ne__', '__neg__', '__new__', '__or__', '__pos__']
['__pow__', '__radd__', '__rand__', '__rdivmod__', '__reduce__']
['__reduce_ex__', '__repr__', '__rfloordiv__', '__rlshift__', '__rmod__']
['__rmul__', '__ror__', '__round__', '__rpow__', '__rrshift__']
['__rshift__', '__rsub__', '__rtruediv__', '__rxor__', '__setattr__']
['__sizeof__', '__str__', '__sub__', '__subclasshook__', '__truediv__']
['__trunc__', '__xor__', 'as_integer_ratio', 'bit_length', 'conjugate']
['denominator', 'from_bytes', 'imag', 'numerator', 'real']
['to_bytes']

['__abs__', '__add__', '__bool__', '__class__', '__delattr__']
['_

In [37]:
# атрибуты объекта
(2+3j).real,(2+3j).imag,(1+3j).__class__

(2.0, 3.0, complex)

In [38]:
# количество разрядов натурального числа ограничено 
# только системой, которой вы пользуетесь
str_num = 10*'1234567890'
print(int(str_num)*1000)
del str_num

1234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890000


In [39]:
# по умолчанию - 10, есть бинарная, восьмеричная, шестнадцатеричная
int('11'),int('11',base=10), \
int('11',base=2),int('11',base=8),int('11',base=16)

In [40]:
# целочисленный, бинарный, восьмеричный и шестнадцатеричный литералы
numbers = [11,0b11,0B11,0o11,0O11,0x11,0X11]
for n in numbers:
    print('|',n,(type(n)),sep='',end='|')

|11<class 'int'>||3<class 'int'>||3<class 'int'>||9<class 'int'>||9<class 'int'>||17<class 'int'>||17<class 'int'>|

In [41]:
# ограничения для вещественных чисел
# самые большие по модулю значения
1.79e308,1.799e308,1.8e308,-1.8e308

In [42]:
# самые близкие к нулю значения
print(1e-323,8e-324,7e-324,5e-324,3e-324,2e-324,1e-325)

1e-323 1e-323 5e-324 5e-324 5e-324 0.0 0.0


In [43]:
# математические операторы
+2,-2,5+7,4-1,2*10,2**10,9/5,9//5,9%5

In [44]:
# встроенные функции
abs(-3),abs(-3+4j),round(1.1111,2),pow(2,10),divmod(9,5)

In [45]:
5*divmod(9,5)[0]+divmod(9,5)[1]==9

True

In [46]:
re,im=3,-4
complex(re,im),re+im*1j,complex(re,im)==re+im*1j

((3-4j), (3-4j), True)

In [47]:
# методы объекта
(21).as_integer_ratio(),complex(3,4).conjugate(),\
(35.41).hex(),float.fromhex('0x1.1b47ae147ae14p+5')

((21, 1), (3-4j), '0x1.1b47ae147ae14p+5', 35.41)

In [48]:
# бинарное представление
number = -124
bin(number),bin(number).lstrip('-0b'),\
number.bit_length(),-0b1111100
# number.bit_count() # python 3.10

('-0b1111100', '1111100', 7, -124)

In [49]:
# побитовое представление
bin(4096).lstrip('-0b'),bin(4097).lstrip('-0b'),\
(4096).to_bytes(2,byteorder='big'),\
(4097).to_bytes(2,byteorder='big'),\
(1024).to_bytes(10,byteorder='big'),\
(-1024).to_bytes(10,byteorder='big',signed=True)

('1000000000000',
 '1000000000001',
 b'\x10\x00',
 b'\x10\x01',
 b'\x00\x00\x00\x00\x00\x00\x00\x00\x04\x00',
 b'\xff\xff\xff\xff\xff\xff\xff\xff\xfc\x00')

In [50]:
(65).to_bytes(1,byteorder='little'),\
(128).to_bytes(1,byteorder='little')

(b'A', b'\x80')

In [51]:
# с помощью модулей - все известные математические преобразования
import math
math.cos(math.pi),math.sin(math.degrees(math.pi/2)),\
math.degrees(math.pi/2)

In [52]:
math.sqrt(625),math.log(1),math.ceil(-7.2),math.ceil(7.2)

In [53]:
# хэширование 
(2).__hash__(),(1024).__hash__(),\
(-2).__hash__(),(10**12).__hash__()